
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_CARD = 'FETCH_USER_CARD';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CREATE_USER = 'CREATE_USER';
export const CREATED_USER = 'CREATED_USER';
export const CREATE_USER_CARD = 'CREATE_USER_CARD';
export const CREATED_USER_CARD = 'CREATED_USER_CARD';
export const CHARGE_USER_CARD = 'CHARGE_USER_CARD';
export const CHARGE_NONCE='CHARGE_NONCE';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_ERROR = 'PURCHASE_ERROR';
export const GET_LOCATION = 'GET_LOCATION';