export const APP_TEST_ACTION = 'APP_TEST_ACTION';
export const APP_TEST_ACTION_DVA = 'APP_TEST_ACTION_DVA';

//CHECKOUT/CART
export const CART_ADD = 'CART_ADD';
export const CART_REMOVE = 'CART_REMOVE';

//NAV
export const NAV_NAVIGATE = 'Navigation/NAVIGATE';
export const NAV_BACK = 'Navigation/BACK';

//WEBVIEWS
export const WEBVIEW_CHEKOUT_MESSAGE_IN='WEBVIEW_CHEKOUT_MESSAGE_IN';
export const WEBVIEW_CHEKOUT_MESSAGE_OUT='WEBVIEW_CHEKOUT_MESSAGE_OUT';
export const WEBVIEW_CHEKOUT_CLEAN_QUE='WEBVIEW_CHEKOUT_CLEAN_QUE';
export const RECEIVED_USER_CARD_NONCE='RECEIVED_USER_CARD_NONCE';

//PAYMENTS
export const PERSIST_PAYMENT_METHOD='PERSIST_PAYMENT_METHOD';
export const PAYMENT_CREATE_NEW='PAYMENT_CREATE_NEW';
export const PAYMENT_BY_CARD='PAYMENT_BY_CARD';
export const PAYMENT_BY_NONCE='PAYMENT_BY_NONCE';
export const PAYMENT_PENDING='PAYMENT_PENDING';
export const PAYMENT_SUCCESS='PAYMENT_SUCCESS';
export const PAYMENT_FAILED='PAYMENT_FAILED';
export const PAYMENT_UPDATE='PAYMENT_UPDATE';

//ORDERS
export const PLACE_ORDER='PLACE_ORDER';

export const NONE = 'NONE';