
//SHOPS
export const SHOP_SELECTED  = 'SHOP_SELECTED';

export const SHOP_CATEGORY_SELECTED         = 'SHOP_CATEGORY_SELECTED';
export const SHOP_CATEGORY_ITEM_SELECTED    = 'SHOP_CATEGORY_ITEM_SELECTED';

export const SHOP_CATEGORY_ITEM_MODIFIER_SELECTED = 'SHOP_CATEGORY_ITEM_MODIFIER_SELECTED';