export const ADDING_CARD='ADDING_CARD';
export const REMOVING_CARD='REMOVING_CARD';

export const USER_CARD_NEW='USER_CARD_ADD';
export const USER_CARD_SAVE='USER_CARD_SAVE';
export const USER_CARD_SELECT='USER_CARD_SELECT';
export const USER_CARD_REMOVE='USER_CARD_REMOVE';

export const USER_NONCE_SAVE='USER_NONCE_SAVE';
export const USER_NONCE_FORM='USER_NONCE_FORM';
export const USER_NONCE_FORM_CLOSE='USER_NONCE_FORM_CLOSE';

export const SETTING_ONE_TIME_PAYMENT='SETTING_ONE_TIME_PAYMENT';
export const MAKING_ORDER='MAKING_ORDER';

export const EDITING_ACCOUNT='EDITING_ACCOUNT';

export const LOGIN_IN='LOGIN_IN';
export const LOGIN_OUT='LOGIN_OUT';

export const UPDATING_USER = 'UPDATING_USER';
export const USER_UPDATED = 'USER_UPDATED';
export const UPDATING_USER_ERROR = 'UPDATING_USER_ERROR';

export const RESET_PASSWORD_REQUEST             = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST_SUCCESS     = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_ERROR       = 'RESET_PASSWORD_REQUEST_ERROR';