
export const GETTING_APP_CONFIG         = 'GETTING_APP_CONFIG';
export const GOT_APP_CONFIG             = 'GOT_APP_CONFIG';
export const GETTING_APP_CONFIG_ERROR   = 'GETTING_APP_CONFIG_ERROR';

export const GETTING_SHOP_IMG_CONFIG         = 'GETTING_SHOP_IMG_CONFIG';
export const GOT_SHOP_IMG_CONFIG              = 'GOT_SHOP_IMG_CONFIG';
export const GETTING_SHOP_IMG_CONFIG_ERROR    = 'GETTING_SHOP_IMG_CONFIG_ERROR';

export const GETTING_AUTHORIZED_SHOPS       = 'GETTING_AUTHORIZED_SHOPS';
export const REFETCHING_AUTHORIZED_SHOPS    = 'REFETCHING_AUTHORIZED_SHOPS';
export const GOT_AUTHORIZED_SHOPS           = 'GOT_AUTHORIZED_SHOPS';
export const GETTING_AUTHORIZED_SHOPS_ERROR = 'GETTING_AUTHORIZED_SHOPS_ERROR';

export const GETTING_SHOP_CATEGORIES        = 'GETTING_SHOP_CATEGORIES';
export const GOT_SHOP_CATEGORIES            = 'GOT_SHOP_CATEGORIES';
export const GETTING_SHOP_CATEGORIES_ERROR  = 'GETTING_SHOP_CATEGORIES_ERROR';

export const CANCELLING_ORDER       = 'CANCELLING_ORDER';
export const ORDER_IS_CANCELLED     = 'ORDER_IS_CANCELLED';
export const CANCELLING_ORDER_ERROR = 'CANCELLING_ORDER_ERROR';

export const REMOVING_ORDER         = 'REMOVING_ORDER';
export const ORDER_IS_REMOVED       = 'ORDER_IS_REMOVED';
export const REMOVING_ORDER_ERROR   = 'REMOVING_ORDER_ERROR';