
export const GETTING_CONFIGS            = 'GETTING_CONFIGS';
export const GOT_CONFIGS                = 'GOT_CONFIGS';
export const GETTING_CONFIGS_ERROR      = 'GETTING_CONFIGS_ERROR';

export const GETTING_AUTHORIZED_SHOPS       = 'GETTING_AUTHORIZED_SHOPS';
export const GOT_AUTHORIZED_SHOPS           = 'GOT_AUTHORIZED_SHOPS';
export const GETTING_AUTHORIZED_SHOPS_ERROR = 'GETTING_AUTHORIZED_SHOPS_ERROR';

export const GETTING_SHOP_CATEGORIES        = 'GETTING_SHOP_CATEGORIES';
export const GOT_SHOP_CATEGORIES            = 'GOT_SHOP_CATEGORIES';
export const GETTING_SHOP_CATEGORIES_ERROR  = 'GETTING_SHOP_CATEGORIES_ERROR';